### ISSUE TITLE
Can't compile native extension on Ruby 1.9.3 on both Linux and OS X, missing thread.h

### ISSUE THREAD

**Issue by NoICE** [eventmachine/eventmachine#507]
https://github.com/eventmachine/eventmachine/blob/c95f1e11c2c0f0e23cd9d4ac2a9c7a75afe54710/ext/em.h#L33

Log from OS X, ruby-1.9.3-p484:

```

Gem::Installer::ExtensionBuildError: ERROR: Failed to build gem native extension.

    /Users/noice/.rvm/rubies/ruby-1.9.3-p484/bin/ruby extconf.rb
checking for rb_trap_immediate in ruby.h,rubysig.h... no
checking for rb_thread_blocking_region()... yes
checking for rb_thread_call_without_gvl()... yes
checking for inotify_init() in sys/inotify.h... no
checking for __NR_inotify_init in sys/syscall.h... no
checking for writev() in sys/uio.h... yes
checking for rb_thread_fd_select()... yes
checking for rb_wait_for_single_fd()... yes
checking for rb_enable_interrupt()... yes
checking for rb_time_new()... yes
checking for sys/event.h... yes
checking for sys/queue.h... yes
creating Makefile

make
compiling binder.cpp
In file included from binder.cpp:20:
In file included from ./project.h:149:
./binder.h:35:3: warning: 'const' type qualifier on return type has no effect [-Wignored-qualifiers]
                const unsigned long GetBinding() {return Binding;}
                ^~~~~~
In file included from binder.cpp:20:
In file included from ./project.h:150:
./em.h:33:13: fatal error: 'ruby/thread.h' file not found
   #include <ruby/thread.h>
            ^
1 warning and 1 error generated.
make: *** [binder.o] Error 1
```

mkmf.log:

```
/Users/noice/.rvm/rubies/ruby-1.9.3-p484/bin/ruby extconf.rb
checking for rb_trap_immediate in ruby.h,rubysig.h... no
checking for rb_thread_blocking_region()... yes
checking for rb_thread_call_without_gvl()... yes
checking for inotify_init() in sys/inotify.h... no
checking for __NR_inotify_init in sys/syscall.h... no
checking for writev() in sys/uio.h... yes
checking for rb_thread_fd_select()... yes
checking for rb_wait_for_single_fd()... yes
checking for rb_enable_interrupt()... yes
checking for rb_time_new()... yes
checking for sys/event.h... yes
checking for sys/queue.h... yes
creating Makefile

make
compiling binder.cpp
In file included from binder.cpp:20:
In file included from ./project.h:149:
./binder.h:35:3: warning: 'const' type qualifier on return type has no effect [-Wignored-qualifiers]
                const unsigned long GetBinding() {return Binding;}
                ^~~~~~
In file included from binder.cpp:20:
In file included from ./project.h:150:
./em.h:33:13: fatal error: 'ruby/thread.h' file not found
   #include <ruby/thread.h>
            ^
1 warning and 1 error generated.
make: *** [binder.o] Error 1
```

It compiles fine with ruby-2.0.0-p353 on the same system.
Tested on Linux with ruby-1.9.3-p429, same result, ruby/thread.h not found.

Change introducing this bug is this one: c95f1e11c2c0f0e23cd9d4ac2a9c7a75afe54710

**Comment by sodabrew** [comment]
This should be resolved in eventmachine 1.0.4. Please give it a try and close the issue or comment with follow-up issues. Thanks!

**Comment by sodabrew** [comment]
Closing assumed to be fixed.
