### ISSUE TITLE
Cannot Install EventMachine w/ Ruby 2.2 on Ubuntu 14.04

### ISSUE THREAD

**Issue by jaredjones** [eventmachine/eventmachine#509]
System: Ubuntu 14.04 Server x64
RAM: 32GB
CPU: Intel E-1240V2
Ruby Version: 2.2.0 Rev: 45614 (Have to use latest ruby as the current stable doesn't work on 14.04)
EventMachine: 1.0.3
# Error Installing Gem:

em::Ext::BuildError: ERROR: Failed to build gem native extension.

 /usr/local/bin/ruby extconf.rb
checking for rb_trap_immediate in ruby.h,rubysig.h... no
checking for rb_thread_blocking_region()... no
checking for inotify_init() in sys/inotify.h... yes
checking for writev() in sys/uio.h... yes
checking for rb_wait_for_single_fd()... yes
checking for rb_enable_interrupt()... no
checking for rb_time_new()... yes
checking for sys/event.h... no
checking for epoll_create() in sys/epoll.h... yes
creating Makefile

make "DESTDIR=" clean

make "DESTDIR="
compiling ssl.cpp
compiling em.cpp
em.cpp: In member function ‘void EventMachine_t::_RunEpollOnce()’:
em.cpp:574:37: error: ‘rb_thread_select’ was not declared in this scope
   EmSelect (0, NULL, NULL, NULL, &tv);
                                     ^
em.cpp: In member function ‘int SelectData_t::_Select()’:
em.cpp:827:67: error: ‘rb_thread_select’ was not declared in this scope
  return EmSelect (maxsocket+1, &fdreads, &fdwrites, &fderrors, &tv);
                                                                   ^
em.cpp: In member function ‘void EventMachine_t::_RunSelectOnce()’:
em.cpp:946:40: error: ‘rb_thread_select’ was not declared in this scope
      EmSelect (0, NULL, NULL, NULL, &tv);
                                        ^
make: **\* [em.o] Error 1

make failed, exit code 2

**Comment by genreil** [comment]
'bundle update eventmachine' worked for me just fine. Thanks!

**Comment by ccoenen** [comment]
:+1:

**Comment by jschorr** [comment]
Thanks for 1.0.4!

**Comment by binarylogic** [comment]
Yes thank you

**Comment by rohandaxini** [comment]
After installing latest "developer tools" for my OSX 10.10.1 Yosemite and Xcode 6.1.1 `bundle update eventmachine` worked for me.

Here is my detailed blog post for resolving this issue with eventmachine gem installation - http://kiprosh.com/blog/208

**Comment by mindaslab** [comment]
Got this error today.

This is my ruby version: ruby 2.2.0p0 (2014-12-25 revision 49005) [x86_64-linux]


```
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    /home/ak/.rvm/rubies/ruby-2.2.0/bin/ruby -r ./siteconf20150414-18212-pn2b1a.rb extconf.rb 
checking for rb_trap_immediate in ruby.h,rubysig.h... no
checking for rb_thread_blocking_region()... no
checking for inotify_init() in sys/inotify.h... yes
checking for writev() in sys/uio.h... yes
checking for rb_wait_for_single_fd()... yes
checking for rb_enable_interrupt()... no
checking for rb_time_new()... yes
checking for sys/event.h... no
checking for epoll_create() in sys/epoll.h... yes
creating Makefile

make "DESTDIR=" clean

make "DESTDIR="
compiling page.cpp
compiling rubymain.cpp
compiling ssl.cpp
compiling cmain.cpp
compiling kb.cpp
compiling ed.cpp
compiling pipe.cpp
compiling binder.cpp
compiling em.cpp
em.cpp: In member function ‘void EventMachine_t::_RunEpollOnce()’:
em.cpp:574:37: error: ‘rb_thread_select’ was not declared in this scope
   EmSelect (0, NULL, NULL, NULL, &tv);
                                     ^
em.cpp: In member function ‘int SelectData_t::_Select()’:
em.cpp:827:67: error: ‘rb_thread_select’ was not declared in this scope
  return EmSelect (maxsocket+1, &fdreads, &fdwrites, &fderrors, &tv);
                                                                   ^
em.cpp: In member function ‘void EventMachine_t::_RunSelectOnce()’:
em.cpp:946:40: error: ‘rb_thread_select’ was not declared in this scope
      EmSelect (0, NULL, NULL, NULL, &tv);
                                        ^
Makefile:229: recipe for target 'em.o' failed
make: *** [em.o] Error 1

make failed, exit code 2

Gem files will remain installed in /home/ak/.rvm/gems/ruby-2.2.0/gems/eventmachine-1.0.3 for inspection.
Results logged to /home/ak/.rvm/gems/ruby-2.2.0/extensions/x86_64-linux/2.2.0/eventmachine-1.0.3/gem_make.out
An error occurred while installing eventmachine (1.0.3), and Bundler cannot
continue.
Make sure that `gem install eventmachine -v '1.0.3'` succeeds before bundling.
```

**Comment by ccoenen** [comment]
@mindaslab this error seems to be from eventmachine 1.0.3, which might be defined in your bundle (Gemfile / Gemfile.lock). From skimming this ticket, I think 1.0.3 is known to not work, and 1.0.4+ appears to fix this.

Did you try updating to a more recent version (at the time of writing 1.0.7 is the current version)? If you are using bundler, you can try `bundle update eventmachine` which will only change eventmachine (and, if neccessary, its dependencies).

**Comment by davidsavoya** [comment]
``` ○ → gem install eventmachine -v '1.0.4'
Building native extensions.  This could take a while...
ERROR:  Error installing eventmachine:
	ERROR: Failed to build gem native extension.

    /Users/development/.rbenv/versions/2.2.0/bin/ruby -r ./siteconf20150414-44585-1wgf0m4.rb extconf.rb
checking for rb_trap_immediate in ruby.h,rubysig.h... no
checking for rb_thread_blocking_region()... no
checking for ruby/thread.h... yes
checking for rb_thread_call_without_gvl() in ruby/thread.h... yes
checking for inotify_init() in sys/inotify.h... no
checking for __NR_inotify_init in sys/syscall.h... no
checking for writev() in sys/uio.h... yes
checking for rb_thread_fd_select()... yes
checking for rb_wait_for_single_fd()... yes
checking for rb_enable_interrupt()... no
checking for rb_time_new()... yes
checking for sys/event.h... yes
checking for sys/queue.h... yes
creating Makefile

make "DESTDIR=" clean

make "DESTDIR="
compiling binder.cpp
In file included from binder.cpp:20:
In file included from ./project.h:29:
In file included from /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/iostream:38:
In file included from /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/ios:216:
In file included from /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/__locale:15:
In file included from /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/string:439:
In file included from /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/algorithm:628:
In file included from /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/memory:604:
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/iterator:341:10: fatal error: '__debug' file not found
#include <__debug>
         ^
1 error generated.
make: *** [binder.o] Error 1

make failed, exit code 2

Gem files will remain installed in /Users/development/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/eventmachine-1.0.4 for inspection.
Results logged to /Users/development/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/extensions/x86_64-darwin-14/2.2.0-static/eventmachine-1.0.4/gem_make.out ``` 
 
I am getting the same error with v 1.0.4 and most recent as well.

**Comment by davidsavoya** [comment]
I think this may be due to new xcode command line tools 6.3. Reverting back to 6.2 solved the issue for me.

**Comment by Empact** [comment]
Seems this error can also be caused by a bug in Xcode Command Line Tools: http://stackoverflow.com/questions/29529455/missing-c-header-debug-after-updating-osx-command-line-tools-6-3

**Comment by adamjgrant** [comment]
I fixed this with `brew link openssl --force`

**Comment by rilian** [comment]
> I fixed this with `brew link openssl --force`

thanks! this helped on a clean install of macos el capitan

**Comment by ulammatha** [comment]
`brew link openssl --force`  worked for OS X el capitan
:+1:

**Comment by rblagahit** [comment]
any fix when using windows?

**Comment by adamjgrant** [comment]
On windows, open up any browser. Go to apple.com/mac and select a machine. Then
click buy. Once the new mac arrives, migrate your data to the mac and try again.

Sent using CloudMagic Email
[https://cloudmagic.com/k/d/mailapp?ct=pi&cv=7.4.8&pv=9.1&source=email_footer_2]
On Thu, Nov 12, 2015 at 1:52 AM, eventmachine/eventmachine
<reply@reply.github.com>
wrote:
any fix when using windows?

—
Reply to this email directly or view it on GitHub
[https://github.com/eventmachine/eventmachine/issues/509#issuecomment-156052581] .[https://github.com/notifications/beacon/AATj7ucPNfi-rn3sGSU-4FHTddefR0EYks5pFFjtgaJpZM4Bzm-h.gif]

**Comment by sodabrew** [comment]
@rblagahit EventMachine 1.0.4 or higher is required for present version of Windows. This thread has become about OpenSSL headers on Mac OS X El Capitan. I'm going to lock the thread now because the stream of +1's isn't adding information.
