### ISSUE TITLE
Failed to build gem version '1.0.3', OSX Yosemite (10.10.2), Ruby 2.2.1p85

### ISSUE THREAD

**Issue by mindware** [eventmachine/eventmachine#599]
I'm requiring a gem that depends upon 1.0.3. 

When I bundle install:

with native extensions
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    /Users/Andres/.rvm/rubies/ruby-2.2.1/bin/ruby -r ./siteconf20150605-2069-k5qwpg.rb extconf.rb
checking for rb_trap_immediate in ruby.h,rubysig.h... no
checking for rb_thread_blocking_region()... no
checking for inotify_init() in sys/inotify.h... no
checking for __NR_inotify_init in sys/syscall.h... no
checking for writev() in sys/uio.h... yes
checking for rb_wait_for_single_fd()... yes
checking for rb_enable_interrupt()... no
checking for rb_time_new()... yes
checking for sys/event.h... yes
checking for sys/queue.h... yes
creating Makefile

make "DESTDIR=" clean

make "DESTDIR="
compiling binder.cpp
compiling cmain.cpp
compiling ed.cpp
compiling em.cpp
em.cpp:827:9: error: use of undeclared identifier 'rb_thread_select'; did you mean 'rb_thread_fd_select'?
        return EmSelect (maxsocket+1, &fdreads, &fdwrites, &fderrors, &tv);
               ^~~~~~~~
               rb_thread_fd_select
./em.h:25:20: note: expanded from macro 'EmSelect'
  #define EmSelect rb_thread_select
                   ^
/Users/Andres/.rvm/rubies/ruby-2.2.1/include/ruby-2.2.0/ruby/intern.h:454:5: note: 'rb_thread_fd_select' declared here
int rb_thread_fd_select(int, rb_fdset_t *, rb_fdset_t *, rb_fdset_t *, struct timeval *);
    ^
em.cpp:827:32: error: cannot initialize a parameter of type 'rb_fdset_t *' with an rvalue of type 'fd_set *'
        return EmSelect (maxsocket+1, &fdreads, &fdwrites, &fderrors, &tv);
                                      ^~~~~~~~
/Users/Andres/.rvm/rubies/ruby-2.2.1/include/ruby-2.2.0/ruby/intern.h:454:42: note: passing argument to parameter here
int rb_thread_fd_select(int, rb_fdset_t *, rb_fdset_t *, rb_fdset_t *, struct timeval *);
                                         ^
em.cpp:946:6: error: use of undeclared identifier 'rb_thread_select'; did you mean 'rb_thread_fd_select'?
                                        EmSelect (0, NULL, NULL, NULL, &tv);
                                        ^~~~~~~~
                                        rb_thread_fd_select
./em.h:25:20: note: expanded from macro 'EmSelect'
  #define EmSelect rb_thread_select
                   ^
/Users/Andres/.rvm/rubies/ruby-2.2.1/include/ruby-2.2.0/ruby/intern.h:454:5: note: 'rb_thread_fd_select' declared here
int rb_thread_fd_select(int, rb_fdset_t *, rb_fdset_t *, rb_fdset_t *, struct timeval *);
    ^
3 errors generated.
make: *** [em.o] Error 1

make failed, exit code 2

Gem files will remain installed in /Users/Andres/.rvm/gems/ruby-2.2.1/gems/eventmachine-1.0.3 for inspection.
Results logged to /Users/Andres/.rvm/gems/ruby-2.2.1/extensions/x86_64-darwin-14/2.2.0-static/eventmachine-1.0.3/gem_make.out

**Comment by sodabrew** [comment]
Please try eventmachine 1.0.7.

**Comment by mindware** [comment]
Thanks, understood. Am I to understand 1.0.3 is broken at this time?

**Comment by sodabrew** [comment]
eventmachine 1.0.3 works great, but it won't compile with Ruby 2.2.

**Comment by mindware** [comment]
Thanks! That was indeed the problem!
